### ISSUE TITLE
Error because of the event name `TerminalOpen` on NeoVim (v0.8.3)

### ISSUE THREAD

**Issue by uniglot** [bronson/vim-trailing-whitespace#29] opened 2023-02-18 06:36 UTC
Hi,

I've been using this plugin quite a long time, but recently I ran into a weird problem complaining like:

<img width="1191" alt="Screenshot 2023-02-18 at 15 29 12" src="https://user-images.githubusercontent.com/18096835/219845169-9625f680-223a-4cfc-953f-066cc90c7557.png">

I think this error must be related to a recent PR (https://github.com/bronson/vim-trailing-whitespace/pull/27), and I suspect that the event name is called differently between Vim and NeoVim.

Is it possible to designate different event names along the different descendants of Vi?

Thank You!

**Comment by uniglot** [comment] 2023-02-18 06:42
#26 seems to be closely related to (or the same with) my issue. I'll leave this issue as open but if you feel redundant, please feel free to close this issue

**Comment by nusendra** [comment] 2023-02-19 18:04
I got this issue too.

**Comment by snipem** [comment] 2023-02-22 13:03
Here is the same error but as text in case any one searches for it:

```
Error detected while processing /Users/matthiaskuech/.vim/plugged/vim-trailing-whitespace/plugin/trailing-whitespace.vim:
line   19:
E216: No such group or event: TerminalOpen * if ShouldMatchWhitespace() | match ExtraWhitespace /\\\@<![\u3000[:space:]]\+$/ | else | match ExtraWhitespace /^^/ | endif
```

**Comment by PabloScolpino** [comment] 2023-02-24 13:46
This is a duplicate of #26

**Comment by PabloScolpino** [comment] 2023-02-24 13:47
PR #30 should Fix this issue.

**Comment by bronson** [comment] 2023-02-28 19:32
Closing because #30 is in. Reopen if you still see an issue.

**Closed by bronson** 2023-02-28 19:32 UTC

**Comment by nidico** [comment] 2023-02-28 19:33
It's fixed for me, thanks!
